# Generated by Django 6.0 on 2026-01-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gamification",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="app_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="gamification",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="gamification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamification_records",
                to="api.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="api.organization",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamification",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "created_at"], name="api_activit_user_id_c1358b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["app_name", "created_at"], name="api_activit_app_nam_737dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["start_time", "end_time"], name="api_activit_start_t_7cf527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamification",
            index=models.Index(
                fields=["user", "date"], name="api_gamific_user_id_f55c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["subdomain"], name="api_organiz_subdoma_866c97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="api_user_email_a7eefd_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["org", "created_at"], name="api_user_org_id_b11b75_idx"
            ),
        ),
    ]
