# Generated by Django 6.0 on 2026-01-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_activitylog_options_alter_gamification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Agent", max_length=255)),
                ("token", models.CharField(max_length=512, unique=True)),
                ("token_expires_at", models.DateTimeField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["token"], name="api_device_token_b0340c_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "last_seen"], name="api_device_user_id_0eb0ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceevent",
            index=models.Index(
                fields=["device", "event"], name="api_devicee_device__cfc31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deviceevent",
            index=models.Index(
                fields=["created_at"], name="api_devicee_created_78396d_idx"
            ),
        ),
    ]
