# Generated by Django 6.0 on 2026-01-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_device_deviceevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("team", "Team")],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_type"], name="api_organiz_organiz_b05e2e_idx"
            ),
        ),
    ]
