# Generated by Django 6.0 on 2026-01-07 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_organization_organization_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("invite_users", "Invite Users"),
                            ("remove_users", "Remove Users"),
                            ("manage_roles", "Manage Roles"),
                            ("view_own_activity", "View Own Activity"),
                            ("view_team_activity", "View Team Activity"),
                            ("export_own_data", "Export Own Data"),
                            ("export_team_data", "Export Team Data"),
                            ("manage_org_settings", "Manage Organization Settings"),
                            ("manage_billing", "Manage Billing"),
                            ("manage_modules", "Manage Modules"),
                            ("create_departments", "Create Departments"),
                            ("manage_departments", "Manage Departments"),
                            ("view_audit_logs", "View Audit Logs"),
                            ("manage_api_keys", "Manage API Keys"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="api.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="api.organization",
                    ),
                ),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_departments",
                        to="api.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("state_changed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="api.organization",
                    ),
                ),
                (
                    "state_changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.permission"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="api.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_in_department", models.CharField(blank=True, max_length=100)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="api.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOrgRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("invitation_expires_at", models.DateTimeField(blank=True, null=True)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to="api.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="api.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_roles",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key_prefix", models.CharField(max_length=8)),
                ("key_hash", models.CharField(max_length=128, unique=True)),
                ("scopes", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="api_apikey_organiz_5f2b0d_idx",
                    ),
                    models.Index(
                        fields=["key_hash"], name="api_apikey_key_has_ce081c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_email", models.EmailField(max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.created", "User Created"),
                            ("user.invited", "User Invited"),
                            ("user.accepted_invitation", "User Accepted Invitation"),
                            ("user.role_changed", "User Role Changed"),
                            ("user.suspended", "User Suspended"),
                            ("user.removed", "User Removed"),
                            ("org.created", "Organization Created"),
                            ("org.state_changed", "Organization State Changed"),
                            ("org.settings_changed", "Organization Settings Changed"),
                            ("permission.granted", "Permission Granted"),
                            ("permission.revoked", "Permission Revoked"),
                            ("dept.created", "Department Created"),
                            ("dept.updated", "Department Updated"),
                            ("dept.deleted", "Department Deleted"),
                            ("data.exported", "Data Exported"),
                            ("data.deleted", "Data Deleted"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.IntegerField(blank=True, null=True)),
                ("changes_before", models.JSONField(blank=True, null=True)),
                ("changes_after", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to="api.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="api_auditlo_organiz_4f46f2_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="api_auditlo_actor_i_f8e456_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="api_auditlo_action_e69819_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="api_auditlo_resourc_c074b3_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "parent_department"],
                name="api_departm_organiz_7ef2d8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="organizationstate",
            index=models.Index(
                fields=["current_state"], name="api_organiz_current_aace55_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AlterUniqueTogether(
            name="userdepartment",
            unique_together={("user", "department")},
        ),
        migrations.AddIndex(
            model_name="userorgrole",
            index=models.Index(
                fields=["organization", "state"], name="api_userorg_organiz_35d132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userorgrole",
            index=models.Index(
                fields=["invitation_token"], name="api_userorg_invitat_bf0b47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userorgrole",
            index=models.Index(fields=["state"], name="api_userorg_state_7aeb0b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userorgrole",
            unique_together={("user", "organization")},
        ),
    ]
