# Generated by Django 6.0 on 2026-01-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_permission_role_department_organizationstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
