# Generated by Django 6.0 on 2026-03-08 10:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_activitylog_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="context_schema_version",
            field=models.CharField(default="1.0", max_length=10),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="data_quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="normalized_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="validation_errors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="context",
            field=models.JSONField(
                blank=True, null=True, validators=[api.models.validate_context_schema]
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["data_quality_score"], name="api_activit_data_qu_990c48_idx"
            ),
        ),
    ]
