# Generated by Django 6.0 on 2026-03-12 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_dataqualitymetrics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="team",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "email_used",
                    models.EmailField(
                        help_text="Email address used to join this org", max_length=254
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("invited", "Invited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="dataqualitymetrics",
            name="unique_daily_org_quality",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="api_device_token_b0340c_idx",
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="api_device_user_id_0eb0ef_idx",
        ),
        migrations.RenameIndex(
            model_name="dataqualitymetrics",
            new_name="api_dataqua_date_58d1b6_idx",
            old_name="api_dataqua_date_org_idx",
        ),
        migrations.RenameIndex(
            model_name="dataqualitymetrics",
            new_name="api_dataqua_organiz_98f04d_idx",
            old_name="api_dataqua_org_date_idx",
        ),
        migrations.RenameIndex(
            model_name="dataqualitymetrics",
            new_name="api_dataqua_updated_75ff6f_idx",
            old_name="api_dataqua_updated_idx",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="api.device",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="device_name",
            field=models.CharField(default="Device", max_length=255),
        ),
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="api.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataqualitymetrics",
            unique_together={("date", "organization")},
        ),
        migrations.AddField(
            model_name="invite",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="auth_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="api.membership",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="api.membership",
            ),
        ),
        migrations.RemoveField(
            model_name="device",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="device",
            name="last_seen",
        ),
        migrations.RemoveField(
            model_name="device",
            name="name",
        ),
        migrations.RemoveField(
            model_name="device",
            name="token",
        ),
        migrations.RemoveField(
            model_name="device",
            name="token_expires_at",
        ),
        migrations.RemoveField(
            model_name="device",
            name="user",
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["auth_user"], name="api_members_auth_us_9f13f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["organization"], name="api_members_organiz_c4a4d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together={("auth_user", "organization")},
        ),
    ]
