# Generated by Django 6.0 on 2026-03-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_invite_membership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="token",
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="device",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["token"], name="api_device_token_b0340c_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["membership", "token"], name="api_device_members_e83cfa_idx"
            ),
        ),
    ]
