# Generated by Django 6.0 on 2026-03-18 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_device_created_at_device_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("user_added", "User Added to Organization"),
                            ("user_role_changed", "User Role Changed"),
                            ("user_removed", "User Removed from Organization"),
                            ("user_invited", "User Invited to Organization"),
                            ("invite_accepted", "Invitation Accepted"),
                            ("org_created", "Organization Created"),
                            ("billing_alert", "Billing Alert"),
                            ("security_alert", "Security Alert"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Extra data: {'member_name': 'John', 'role': 'admin', etc}",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="api_notific_recipie_0f27ac_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_read", "-created_at"],
                        name="api_notific_organiz_956972_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="api_notific_notific_0fa80a_idx",
                    ),
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="api_notific_recipie_5c719b_idx",
                    ),
                ],
            },
        ),
    ]
